name: CI/CD Pipeline for .NET Console App

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]  # Add more OSes if needed (e.g., macos-latest)
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Cache .NET dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx"

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}
        path: TestResults/
      if: always()

    - name: Publish Standalone Executable
      run: dotnet publish --configuration Release -r ${{ matrix.runtime }} --self-contained -o ./publish

    - name: Compress Artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: Compress-Archive -Path .\publish\* -DestinationPath ConApp1Net8ActionBuildTest-windows.zip

    - name: Compress Artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p ConApp1Net8ActionBuildTest-linux
        cp -r ./publish/* ConApp1Net8ActionBuildTest-linux/
        tar -czvf ConApp1Net8ActionBuildTest-linux.tar.gz ConApp1Net8ActionBuildTest-linux

    - name: Clean Up (Optional)
      shell: pwsh  # Use PowerShell Core
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          Remove-Item -Recurse -Force ./publish
        } else {
          rm -rf ./publish
        }

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConApp1Net8ActionBuildTest-${{ matrix.os }}
        path: |
          ConApp1Net8ActionBuildTest-windows.zip
          ConApp1Net8ActionBuildTest-linux.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ConApp1Net8ActionBuildTest-v${{ github.run_number }}
        name: ConApp1Net8ActionBuildTest Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          ./artifacts/ConApp1Net8ActionBuildTest-windows-latest/ConApp1Net8ActionBuildTest-windows.zip
          ./artifacts/ConApp1Net8ActionBuildTest-ubuntu-latest/ConApp1Net8ActionBuildTest-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
